version: '3'
services:
  my-sql:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=db_pass123
      - MYSQL_DATABASE=website
      - MYSQL_USER=php_user
      - MYSQL_PASSWORD=php_pass
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql-db
      - MYSQL_ROOT_PASSWORD=db_pass123